module.exports = {
  responses: {
    USER_CREATED_OK: 'USER_SUCCESSFULLY_CREATED',
    USER_LOGGED_IN: 'USER_SUCCESSFULLY_LOGGED_IN'
  },
  errors: {
    DATABASE_ERROR: 'DATABASE_ERROR',
    DEFAULT_ERROR: 'DEFAULT_SERVER_ERROR',
    BAD_LOGIN_ERROR: 'BAD_LOGIN_EROR'
  }
};
